import React, { useState } from 'react';
import { ArrowRight, Play, MagnifyingGlassPlus, Lightning, Buildings, Elevator, Drop, Camera, Plus } from '@phosphor-icons/react';
import { address, type PageKey } from './data';

export type Media = { src:string; poster:string; title:string; caption:string };
export type ImageView = { src:string; title:string; alt:string };
type Actions = { onMedia:(media:Media)=>void; onImage:(image:ImageView)=>void; onRequest:(text:string)=>void };
export const electricityMedia:Media = {src:'/video/electricity.mp4',poster:'/images/electricity.webp',title:'Жительница об электроснабжении',caption:'Отзыв жительницы о подключении второй линии. Личный опыт, записанный в квартале.'};
const familyMedia:Media = {src:'/video/community-event.mp4',poster:'/images/community-event.webp',title:'Праздник, который объединяет соседей',caption:'Мероприятие для жителей Новой Пальмиры. События и семейные активности во дворе.'};

export function ChapterNav(){return <nav className="chapter-nav section-shell" aria-label="Разделы главной"><a href="#family">Семейная среда</a><a href="#power">Электроснабжение</a><a href="#plans">Планировки</a><a href="#neighborhood">Инфраструктура</a><a href="#purchase">Покупка</a></nav>;}

export function FamilySection({onMedia}:Pick<Actions,'onMedia'>){return <section id="family" className="editorial-section section-shell family-section" aria-labelledby="family-title">
  <div className="editorial-heading"><div><p className="eyebrow">Семейная среда</p><h2 id="family-title">Дети растут.<br/>Соседи становятся друзьями.</h2></div><p>Дом продолжается за порогом квартиры — на детской площадке, на прогулке и на празднике, который собирает весь двор.</p></div>
  <div className="family-gallery"><figure><img src="/images/playground.webp" alt="Детская площадка во дворе Новой Пальмиры" loading="lazy"/><figcaption>Свой двор для маленьких открытий</figcaption></figure><button className="family-film" onClick={()=>onMedia(familyMedia)} aria-label="Смотреть видео семейного праздника"><img src="/images/community-event.webp" alt="Участницы праздника для жителей квартала" loading="lazy"/><span className="film-action"><span className="play-outline"><Play size={16} weight="fill"/></span>События для соседей</span></button></div>
  <div className="editorial-facts"><article><h3>Дворы для детей</h3><p>Игровые площадки и прогулочные пространства внутри квартала.</p></article><article><h3>Встречи рядом с домом</h3><p>Семейные активности, дворовые праздники и знакомые лица.</p></article><article><h3>Повседневные дела рядом</h3><p>Детский сад, магазины и сервисы на первых этажах.</p></article></div>
</section>;}

export function PowerSection({onMedia}:Pick<Actions,'onMedia'>){return <section id="power" className="power-band" aria-labelledby="power-title"><div className="section-shell power-grid">
  <div><p className="eyebrow"><Lightning size={18}/> Электроснабжение квартала</p><h2 id="power-title">Два ввода.<br/>Больше устойчивости.</h2><p>Отдельная линия от подстанции «Приозёрная» и второй независимый ввод снижают зависимость квартала от одной внешней линии.</p><a className="button" href="/elektrosnabzhenie">Как устроено питание<ArrowRight size={18}/></a></div>
  <div className="power-proof"><blockquote>«Спасибо, что провели, сдержали слово, провели вторую линию»</blockquote><p>Из видеоотзыва жительницы квартала</p><button className="video-link" onClick={()=>onMedia(electricityMedia)}><span className="play-outline"><Play size={15} weight="fill"/></span>Смотреть отзыв об электроснабжении</button><div className="power-labels"><span>Отдельная линия</span><span>Независимый резерв</span></div></div>
</div></section>;}

export function PowerDetails({onRequest}:Pick<Actions,'onRequest'>){return <section className="editorial-section section-shell power-details" aria-labelledby="power-systems-title">
  <div className="editorial-heading"><div><p className="eyebrow">Что зависит от питания</p><h2 id="power-systems-title">Комфорт складывается<br/>из работающих систем.</h2></div><p>Электричество нужно и внутри квартиры, и в общих пространствах дома. Резервный ввод — часть инженерного решения квартала.</p></div>
  <div className="system-grid">{[{icon:Buildings,title:'Квартиры',text:'Свет и бытовая техника.'},{icon:Elevator,title:'Лифты',text:'Доступ к вашему этажу.'},{icon:Drop,title:'Насосы и котельная',text:'Инженерные системы дома.'},{icon:Camera,title:'Территория',text:'Освещение и видеонаблюдение.'}].map(({icon:Icon,title,text})=><article key={title}><Icon size={30} weight="light"/><h3>{title}</h3><p>{text}</p></article>)}</div>
  <div className="power-explanation"><p>Два ввода повышают устойчивость электроснабжения. Плановые работы и локальные неисправности по-прежнему возможны; порядок переключения и обслуживание оборудования можно обсудить с командой квартала.</p><button className="text-link" onClick={()=>onRequest('Вопросы об электроснабжении выбранного корпуса')}>Задать вопрос об инженерии<ArrowRight size={18}/></button></div>
</section>;}

export function Infrastructure({onMedia}:Pick<Actions,'onMedia'>){return <section id="neighborhood" className="editorial-section section-shell infrastructure-section" aria-labelledby="infrastructure-title">
  <div className="editorial-heading"><div><p className="eyebrow">Инфраструктура и парковки</p><h2 id="infrastructure-title">Ваш привычный маршрут.<br/>Теперь — короче.</h2></div><p>Забрать заказ, купить продукты, отвести ребёнка в сад. Повседневные сервисы становятся частью прогулки по кварталу.</p></div>
  <div className="infrastructure-grid"><img src="/images/infrastructure.webp" alt="Работающие магазины и сервисы на первых этажах квартала" loading="lazy"/><div className="place-list"><article><span>01</span><div><h3>Детский сад</h3><p>Panda Premium на территории квартала.</p></div></article><article><span>02</span><div><h3>Покупки и заказы</h3><p>«Магнит», Ozon, Wildberries и другие повседневные сервисы.</p></div></article><article><span>03</span><div><h3>Место для автомобиля</h3><p>Две крытые парковки и парковочные места вдоль улиц и домов. Доступность мест уточняется отдельно.</p></div></article><button className="text-link" onClick={()=>onMedia({src:'/video/infrastructure.mp4',poster:'/images/infrastructure.webp',title:'Инфраструктура Новой Пальмиры',caption:'Знакомство с окружением и сервисами квартала.'})}>Посмотреть окружение<ArrowRight size={18}/></button></div></div>
</section>;}

const stages=[['1-й этап','2019'],['2-й этап','2020'],['3-й этап','2021'],['4-й этап','2022'],['5-й этап','2024'],['6-й этап','2025']];
export function QuarterPlan({onImage,onRequest}:Pick<Actions,'onImage'|'onRequest'>){return <section id="quarter-plan" className="editorial-section section-shell quarter-section" aria-labelledby="quarter-title">
  <div className="editorial-heading"><div><p className="eyebrow">Готовый квартал и новые очереди</p><h2 id="quarter-title">Посмотрите, где<br/>будет ваш дом.</h2></div><p>{address}. На схеме можно сопоставить этапы строительства, расположение домов и территорию между ними.</p></div>
  <div className="quarter-map-layout"><button className="quarter-map" onClick={()=>onImage({src:'/images/scheme.jpg',title:'Схема квартала',alt:'Схема этапов строительства Новой Пальмиры'})} aria-label="Увеличить схему квартала"><img src="/images/scheme.jpg" alt="Схема домов и этапов строительства Новой Пальмиры" loading="lazy"/><span className="zoom-hint"><MagnifyingGlassPlus size={18}/>Увеличить схему</span></button><div className="stage-summary"><p className="eyebrow">По схеме проекта</p><h3>Сданные этапы</h3><dl>{stages.map(([stage,year])=><div key={stage}><dt>{stage}</dt><dd>{year}</dd></div>)}</dl><div className="next-stages"><h3>Развитие квартала</h3><p>7-й этап — 2028, 8-й — 2030.<br/>Плановые сроки по схеме проекта.</p></div><button className="text-link" onClick={()=>onRequest('Наличие квартир и актуальная готовность корпусов')}>Уточнить готовность и наличие<ArrowRight size={18}/></button><a className="text-link" href={`https://yandex.ru/maps/?text=${encodeURIComponent(address+' Новая Пальмира')}`} target="_blank" rel="noreferrer">Построить маршрут<ArrowRight size={18}/></a></div></div>
</section>;}

export function PurchaseSection({onRequest,selected=''}:Pick<Actions,'onRequest'>&{selected?:string}){
  const [payment,setPayment]=useState('Рассрочка');const [deposit,setDeposit]=useState('Обсудить взнос');const [term,setTerm]=useState('Подобрать срок');
  return <section id="purchase" className="purchase-band" aria-labelledby="purchase-title"><div className="section-shell purchase-layout"><div><p className="eyebrow">Условия покупки</p><h2 id="purchase-title">Квартира — ваша.<br/>Платежи — под ваш план.</h2><p>Начните с удобного способа оплаты. Менеджер подготовит стоимость и доступный график платежей для выбранного объекта.</p><ol className="purchase-steps"><li>Выбираем квартиру и проверяем наличие</li><li>Согласовываем взнос, срок и платежи</li><li>Знакомимся с документами и договором</li></ol></div><form className="purchase-options" onSubmit={e=>{e.preventDefault();onRequest(`${selected||'Подбор квартиры'}. Оплата: ${payment}${payment==='Рассрочка'?`; взнос: ${deposit}; срок: ${term}`:''}`);}}><h3>Ваши пожелания к покупке</h3>{selected&&<p className="purchase-selection">{selected}</p>}<label>Способ оплаты<select aria-label="Способ оплаты" value={payment} onChange={e=>setPayment(e.target.value)}><option>Рассрочка</option><option>Полная оплата</option><option>Нужна консультация</option></select></label>{payment==='Рассрочка'&&<div className="purchase-select-row"><label>Первоначальный взнос<select aria-label="Первоначальный взнос" value={deposit} onChange={e=>setDeposit(e.target.value)}><option>Обсудить взнос</option><option>До 30%</option><option>30–50%</option><option>Более 50%</option></select></label><label>Желаемый срок<select aria-label="Желаемый срок" value={term} onChange={e=>setTerm(e.target.value)}><option>Подобрать срок</option><option>До 1 года</option><option>1–3 года</option><option>Более 3 лет</option></select></label></div>}<p className="purchase-note">Это ваши пожелания. Доступный срок, взнос и итоговую стоимость подтвердит менеджер.</p><button className="button" type="submit">Получить персональный расчёт<ArrowRight size={18}/></button></form></div></section>;
}

export function QualitySection({developer=false,onRequest}:Pick<Actions,'onRequest'>&{developer?:boolean}){return <section id="quality" className="editorial-section section-shell quality-section" aria-labelledby="quality-title"><div className="quality-grid"><img src="/images/staircase.jpg" alt="Реальная отделка лестниц и общих пространств дома" loading="lazy"/><div><p className="eyebrow">Качество, которое можно увидеть</p><h2 id="quality-title">От конструкции дома<br/>до деталей подъезда.</h2><div className="quality-list"><article><h3>Кирпич и монолит</h3><p>Монолитный каркас и кладка наружных стен.</p></article><article><h3>Вентилируемый фасад</h3><p>Внешний облик и защита фасадной конструкции.</p></article><article><h3>Безригельные перекрытия</h3><p>Чистая геометрия потолка и гибкость пространства.</p></article><article><h3>Лифты и общие зоны</h3><p>Готовые подъезды и оборудование можно оценить на просмотре. Комплектацию сверяем по выбранному корпусу.</p></article></div>{developer?<button className="text-link" onClick={()=>onRequest('Просмотр готового дома и характеристики выбранного корпуса')}>Посмотреть готовый дом<ArrowRight size={18}/></button>:<a className="text-link" href="/zastroishchik">О застройщике и качестве домов<ArrowRight size={18}/></a>}</div></div></section>;}

export function ManagementDetails({onRequest}:Pick<Actions,'onRequest'>){return <section className="editorial-section section-shell management-services" aria-labelledby="service-title"><div className="editorial-heading"><div><p className="eyebrow">Мегаполис Комфорт</p><h2 id="service-title">Забота о доме —<br/>конкретные дела.</h2></div><p>Содержание общих пространств, обслуживание оборудования и связь с жителями продолжаются после получения ключей.</p></div><div className="editorial-facts"><article><h3>Обращения в приложении</h3><p>Заявки по дому и оплата коммунальных услуг. Порядок подключения подскажет управляющая компания.</p></article><article><h3>Видеонаблюдение</h3><p>Камеры в подъездах, дворах и лифтах. Вопросы доступа и обслуживания — в УК.</p></article><article><h3>Уход за территорией</h3><p>Уборка, озеленение, сезонные работы и обслуживание общих зон.</p></article></div><button className="text-link" onClick={()=>onRequest('Услуги УК, приложение для жителей и обслуживание дома')}>Уточнить обслуживание дома<ArrowRight size={18}/></button></section>;}

export function CompanyInfo({onRequest}:Pick<Actions,'onRequest'>){return <section id="company-info" className="editorial-section section-shell company-section" aria-labelledby="company-title"><div><p className="eyebrow">Мегаполис Групп</p><h2 id="company-title">Познакомиться с компанией.<br/>Разобраться в документах.</h2><p>В офисе продаж можно сверить сведения о компании, выбранном корпусе и квартире, обсудить договор и график платежей.</p><button className="button" onClick={()=>onRequest('Документы по выбранному корпусу, договор и график платежей')}>Запросить документы<ArrowRight size={18}/></button></div><div className="company-details"><h3>ООО «МЕГАПОЛИС-ГРУПП»</h3><dl><div><dt>ИНН</dt><dd>0571017584</dd></div><div><dt>КПП</dt><dd>057101001</dd></div><div><dt>ОГРН</dt><dd>1210500000402</dd></div><div><dt>Офис</dt><dd>{address}</dd></div></dl><p>Состав документов и сторона договора определяются выбранным объектом. Перед оформлением менеджер предоставит сведения по вашей сделке.</p></div></section>;}

export function ResidentStories({onImage}:Pick<Actions,'onImage'>){const reviews=[{name:'Зумруд Хайруллаева',date:'3 июня 2026',quote:'Выдали ключи вовремя, стройкой не затянули.',image:'/images/review-01.webp'},{name:'Аминат Муртузалиева',date:'9 августа 2026',quote:'Квартира с шикарным видом, очень рады!',image:'/images/review-02.webp'},{name:'Зумрут Алиева',date:'3 августа 2026',quote:'Прекрасная компания, гостеприимны, компетентны и профессиональны.',image:'/images/review-03.webp'}];return <section id="residents" className="editorial-section section-shell residents-section" aria-labelledby="residents-title"><div className="editorial-heading"><div><p className="eyebrow">Опыт покупателей</p><h2 id="residents-title">Истории тех,<br/>кто уже получил ключи.</h2></div><p>О покупке, выдаче ключей и общении с командой — в отзывах клиентов. Каждый отзыв можно открыть целиком.</p></div><div className="review-grid">{reviews.map(r=><article key={r.name}><blockquote>«{r.quote}»</blockquote><div><p className="review-name">{r.name}</p><p className="review-date">{r.date}</p><button className="text-link" onClick={()=>onImage({src:r.image,title:`Отзыв · ${r.name}`,alt:`Оригинальный скриншот отзыва ${r.name}`})}>Открыть оригинал<ArrowRight size={17}/></button></div></article>)}</div></section>;}

export function NeighborhoodSummary({pageKey}: {pageKey:PageKey}){return <section className="neighborhood-summary section-shell" aria-label="Жизнь в квартале"><p className="eyebrow">Вместе с вашей квартирой</p><div><a href="/#family"><h3>Семейная среда</h3><p>Дворы, площадки и события для соседей.</p><ArrowRight size={20}/></a><a href={pageKey==='electricity'?'#power-systems-title':'/elektrosnabzhenie'}><h3>Два ввода питания</h3><p>Отдельная линия и независимый резерв.</p><ArrowRight size={20}/></a><a href="/#neighborhood"><h3>Сервисы рядом</h3><p>Детский сад, магазины и парковки.</p><ArrowRight size={20}/></a></div></section>;}

export function SpecializedDetails({kind,onRequest}:Pick<Actions,'onRequest'>&{kind:'mansards'|'commercial'}){const mansard=kind==='mansards';const [area,setArea]=useState('');const [purpose,setPurpose]=useState('');return <section id="object-selection" className="editorial-section section-shell specialized-details" aria-labelledby="specialized-title"><div><p className="eyebrow">{mansard?'Мансарды':'Коммерческие помещения'} · Детали выбора</p><h2 id="specialized-title">{mansard?'Планируем жизнь\nпод самой крышей.':'Пространство\nдля вашего дела.'}</h2><p>{mansard?'Верхний уровень, особенная геометрия и отсутствие соседей сверху. На просмотре сравните полезную площадь, расположение окон и высоту потолка в разных точках.':'Сопоставьте расположение помещения с форматом бизнеса. Важны не только метры: вход, фасад, коммуникации и подходы к помещению.'}</p><div className="special-parameters">{(mansard?['План и разрез потолка','Окна и полезная площадь','Доступ на этаж и кровля']:['План и расположение входа','Мощность и коммуникации','Назначение и условия покупки']).map(text=><p key={text}><Plus size={16}/>{text}</p>)}</div></div><form onSubmit={e=>{e.preventDefault();onRequest(`${mansard?'Подбор мансарды':'Подбор коммерческого помещения'}${area?`; площадь: ${area} м²`:''}${purpose?`; ${purpose}`:''}`);}}><h3>Подборка под ваш запрос</h3><label>Желаемая площадь, м²<input type="number" min="1" max="10000" value={area} onChange={e=>setArea(e.target.value)} placeholder={mansard?'Например, 100':'Например, 80'}/></label><label>{mansard?'Что важно в планировке':'Для какого бизнеса'}<input value={purpose} onChange={e=>setPurpose(e.target.value)} maxLength={100} placeholder={mansard?'Спальни, рабочее место, хранение':'Магазин, офис, студия…'}/></label><p className="purchase-note">Получите доступные варианты, их точные планы и параметры от команды проекта.</p><button className="button" type="submit">Запросить планы и параметры<ArrowRight size={18}/></button></form></section>;}
